import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import { formatPaiseForPdf } from "@/lib/currency";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 16, fontWeight: 700 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label: { color: "#555" },
  section: { marginTop: 20, marginBottom: 8, fontSize: 13, fontWeight: 700 },
  tc: { marginTop: 8, lineHeight: 1.5, color: "#333" },
  signatureRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 },
  signatureBox: { width: "45%" },
  signatureImage: { height: 60, objectFit: "contain", marginBottom: 4 },
  signatureLine: { borderTopWidth: 1, borderTopColor: "#999", paddingTop: 4 },
  signatureCaption: { fontSize: 9, color: "#555" },
  pending: { fontSize: 9, color: "#999", fontStyle: "italic" },
});

interface AgreementProps {
  loan: {
    id: number;
    principalPaise: number;
    annualRatePercent: number;
    tenureMonths: number;
    repaymentType: "EMI" | "INTEREST_ONLY";
    emiPaise: number;
    totalInterestPaise: number;
    finalTotalPaise: number;
    startDate: number;
  };
  contact: { name: string };
  lenderSignatureDataUri: string | null;
  borrowerSignatureDataUri: string | null;
}

function fmtDate(ms: number) {
  return new Date(ms).toLocaleDateString("en-IN");
}

export function AgreementDocument({
  loan,
  contact,
  lenderSignatureDataUri,
  borrowerSignatureDataUri,
}: AgreementProps) {
  const finalMonthPaymentPaise = loan.emiPaise + loan.principalPaise;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Happy Lending — Loan Agreement</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Contact</Text>
          <Text>{contact.name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Principal</Text>
          <Text>{formatPaiseForPdf(loan.principalPaise)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Interest rate</Text>
          <Text>{loan.annualRatePercent}% p.a.</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total interest</Text>
          <Text>{formatPaiseForPdf(loan.totalInterestPaise)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Tenure</Text>
          <Text>{loan.tenureMonths} months</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Repayment type</Text>
          <Text>
            {loan.repaymentType === "INTEREST_ONLY"
              ? "Interest-only (principal at the end)"
              : "EMI (equal monthly installments)"}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>
            {loan.repaymentType === "INTEREST_ONLY" ? "Monthly interest" : "EMI"}
          </Text>
          <Text>{formatPaiseForPdf(loan.emiPaise)} / month</Text>
        </View>
        {loan.repaymentType === "INTEREST_ONLY" && (
          <View style={styles.row}>
            <Text style={styles.label}>Final month payment</Text>
            <Text>{formatPaiseForPdf(finalMonthPaymentPaise)}</Text>
          </View>
        )}
        <View style={styles.row}>
          <Text style={styles.label}>Total payable</Text>
          <Text>{formatPaiseForPdf(loan.finalTotalPaise)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Start date</Text>
          <Text>{fmtDate(loan.startDate)}</Text>
        </View>

        <Text style={styles.section}>Terms &amp; Conditions</Text>
        <Text style={styles.tc}>
          This document certifies that a loan of {formatPaiseForPdf(loan.principalPaise)} is
          given to {contact.name} on {fmtDate(loan.startDate)}, recorded via the Happy Lending
          app. Total amount payable over the tenure: {formatPaiseForPdf(loan.finalTotalPaise)}{" "}
          (Principal {formatPaiseForPdf(loan.principalPaise)} + Interest{" "}
          {formatPaiseForPdf(loan.totalInterestPaise)}).
          {"\n\n"}
          1. This document is a personal record generated by the Happy Lending app and does
          not constitute a legally binding contract.{"\n"}
          2. Both parties acknowledge the above loan terms as the agreed basis for
          repayment.{"\n"}
          3. Any future dispute relating to this transaction shall be resolved amicably
          between the parties.{"\n"}
          4. A separate closure statement will be issued once this loan is fully repaid.
        </Text>

        <Text style={styles.section}>Signatures</Text>
        <View style={styles.signatureRow}>
          <View style={styles.signatureBox}>
            {lenderSignatureDataUri && (
              <Image style={styles.signatureImage} src={lenderSignatureDataUri} />
            )}
            <View style={styles.signatureLine}>
              <Text style={styles.signatureCaption}>Lender</Text>
              {!lenderSignatureDataUri && (
                <Text style={styles.pending}>Not yet signed</Text>
              )}
            </View>
          </View>
          <View style={styles.signatureBox}>
            {borrowerSignatureDataUri && (
              <Image style={styles.signatureImage} src={borrowerSignatureDataUri} />
            )}
            <View style={styles.signatureLine}>
              <Text style={styles.signatureCaption}>Borrower ({contact.name})</Text>
              {!borrowerSignatureDataUri && (
                <Text style={styles.pending}>Not yet signed</Text>
              )}
            </View>
          </View>
        </View>
      </Page>
    </Document>
  );
}
